apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: APP_IMAGE
    newName: acrhankaksgitops001.azurecr.io/azure-aks-gitops-app
    newTag: initial